-- 코드를 입력하세요
SELECT MONTH(START_DATE) AS MONTH,CAR_ID,COUNT(CAR_ID) AS RECORDS 
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID
IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE LEFT(START_DATE,7) BETWEEN '2022-08' AND '2022-10' 
    GROUP BY CAR_ID
    HAVING COUNT(CAR_ID) >= 5
)
AND LEFT(START_DATE,7) BETWEEN '2022-08' AND '2022-10'
GROUP BY CAR_ID, MONTH(START_DATE)
HAVING RECORDS >=1
ORDER BY MONTH, CAR_ID DESC;
