SELECT P.PRODUCT_CODE, SUM(P.PRICE * O.SALES_AMOUNT) AS SALES
  FROM PRODUCT AS P
  JOIN (SELECT * FROM OFFLINE_SALE) AS O
 WHERE P.PRODUCT_ID = O.PRODUCT_ID
 GROUP BY PRODUCT_CODE
 ORDER BY SUM(P.PRICE * O.SALES_AMOUNT) DESC, P.PRODUCT_CODE ASC