SELECT F.FLAVOR
  FROM (
      SELECT SHIPMENT_ID, FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
        FROM FIRST_HALF  
       GROUP BY FLAVOR
    ) AS F
    JOIN (
      SELECT SHIPMENT_ID, FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
        FROM JULY 
       GROUP BY FLAVOR
        ) AS J
  WHERE F.FLAVOR = J.FLAVOR
  ORDER BY F.TOTAL_ORDER + J.TOTAL_ORDER DESC
  LIMIT 3