-- 코드를 입력하세요
SELECT DATE_FORMAT(A.SALES_DATE,"%Y-%m-%d") as SALES_DATE,A.PRODUCT_ID,A.USER_ID,A.SALES_AMOUNT
FROM (
    SELECT ONLINE_SALE_ID,USER_ID,PRODUCT_ID,SALES_AMOUNT,SALES_DATE FROM ONLINE_SALE
    UNION ALL
    SELECT OFFLINE_SALE_ID ,NULL AS USER_ID,PRODUCT_ID,SALES_AMOUNT,SALES_DATE FROM OFFLINE_SALE
    )AS A
WHERE LEFT(A.SALES_DATE,7)='2022-03'
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC;
