SELECT DATE_FORMAT(os.SALES_DATE, %Y-%m-%d) AS SALES_DATE, os.PRODUCT_ID, os.USER_ID, os.SALES_AMOUNT
FROM ONLINE_SALE os
WHERE YEAR(os.SALES_DATE) = 2022 AND MONTH(os.SALES_DATE) = 3
UNION ALL
SELECT DATE_FORMAT(ofs.SALES_DATE, %Y-%m-%d) AS SALES_DATE, ofs.PRODUCT_ID, NULL AS USER_ID, ofs.SALES_AMOUNT
FROM OFFLINE_SALE ofs
WHERE YEAR(ofs.SALES_DATE) = 2022 AND MONTH(ofs.SALES_DATE) = 3
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;
