SELECT ALL_HOURS.HOUR, COUNT(HOUR_COUNT.ANIMAL_ID) AS COUNT
FROM (
  SELECT DATE_FORMAT(DATETIME, '%H') AS HOUR, ANIMAL_ID
  FROM ANIMAL_OUTS
) AS HOUR_COUNT
RIGHT OUTER JOIN (
  SELECT '00' AS HOUR
  UNION SELECT '01' AS HOUR
  UNION SELECT '02' AS HOUR
  UNION SELECT '03' AS HOUR
  UNION SELECT '04' AS HOUR
  UNION SELECT '05' AS HOUR
  UNION SELECT '06' AS HOUR
  UNION SELECT '07' AS HOUR
  UNION SELECT '08' AS HOUR
  UNION SELECT '09' AS HOUR
  UNION SELECT '10' AS HOUR
  UNION SELECT '11' AS HOUR
  UNION SELECT '12' AS HOUR
  UNION SELECT '13' AS HOUR
  UNION SELECT '14' AS HOUR
  UNION SELECT '15' AS HOUR
  UNION SELECT '16' AS HOUR
  UNION SELECT '17' AS HOUR
  UNION SELECT '18' AS HOUR
  UNION SELECT '19' AS HOUR
  UNION SELECT '20' AS HOUR
  UNION SELECT '21' AS HOUR
  UNION SELECT '22' AS HOUR
  UNION SELECT '23' AS HOUR
) AS ALL_HOURS
ON HOUR_COUNT.HOUR = ALL_HOURS.HOUR
GROUP BY ALL_HOURS.HOUR
ORDER BY ALL_HOURS.HOUR;
