SELECT YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER, COUNT(DISTINCT I.USER_ID) AS USERS
  FROM USER_INFO I
  JOIN ONLINE_SALE S
    ON I.USER_ID = S.USER_ID
 WHERE GENDER != NULL
 GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
 ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER