SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(S.CNT * B.PRICE) AS TOTAL_SALES
  FROM BOOK AS B, AUTHOR AS A, (SELECT BOOK_ID, SUM(SALES) AS CNT
                                  FROM BOOK_SALES
                                 WHERE MONTH(SALES_DATE) = 1
                                 GROUP BY BOOK_ID) AS S
 WHERE B.BOOK_ID = S.BOOK_ID AND B.AUTHOR_ID = A.AUTHOR_ID
 GROUP BY B.CATEGORY, A.AUTHOR_ID
 ORDER BY A.AUTHOR_ID, B.CATEGORY DESC