SELECT CAR_ID,
  CASE 
    WHEN EXISTS (SELECT * FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
                 WHERE CAR_ID = c.CAR_ID 
                 AND START_DATE <= '2022-10-16' 
                 AND END_DATE >= '2022-10-16') 
    THEN '대여중'
    ELSE '대여 가능'
  END AS AVAILABILITY
FROM (SELECT DISTINCT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) AS c
ORDER BY CAR_ID DESC;
